another chapter in Practical Robot
G1ANT-Robot/G1ANT.Manual pull request #29
Opened 2019-01-28 12:03 UTC by Vegebutcher

@lfronczyk There's a part with your C# snippet for character conversion. Please take a look at its description.

2019-02-04 15:10 UTC, WiktoriaPrusik requested changes
Everything is fine, just change to camel case everywhere, please

2019-02-04 15:10 UTC, WiktoriaPrusik commented on g1ant-language/practical-robot/04-web-scraping.md
> +    selenium.seturl ♥yahoourl
camel :)

2019-02-04 15:10 UTC, WiktoriaPrusik commented on g1ant-language/practical-robot/04-web-scraping.md
> +Sheet happens: the Robot encounters a problem right after it opens your Google Sheets document and tries to set the first cell’s value. The error message reads *“Input string was not in a correct for
sheet happens 😂😂😂

2019-02-05 15:51 UTC, lfronczyk approved these changes

2019-02-05 16:44 UTC, merged